name: itop-api-gw

services:

  api-gw:
    build:
      dockerfile: Dockerfile
    environment:
      ITOP_HOSTS: http://itop
      CORS_ALLOW_ORIGINS: "http://localhost:8080" # swagger ui
    ports:
      - "8000:8000"
    volumes:
       - ./out:/etc/krakend/out # for debug only
    restart: unless-stopped

  swagger:
    image: swaggerapi/swagger-ui:${SWAGGER_VERSION:-latest}
    environment:
      # https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
      URL: /specs/open-api.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./open-api.yaml:/usr/share/nginx/html/specs/open-api.yaml
    restart: unless-stopped

  itop:
    image: vbkunin/itop:${ITOP_VERSION:-latest}
    environment:
      MYSQL_PASS: 'admin'
    ports:
      - "8001:80"
    volumes:
      - itop-db-volume:/var/lib/mysql
      - itop-conf-volume:/var/www/html/conf
    restart: unless-stopped

volumes:
  itop-db-volume:
  itop-conf-volume: